CREATE DATABASE IF NOT EXISTS COST_EXPLORER_DB;
CREATE SCHEMA IF NOT EXISTS COST_EXPLORER_DB.APPS;
CREATE STAGE IF NOT EXISTS COST_EXPLORER_DB.APPS.STREAMLIT_STAGE;

USE DATABASE COST_EXPLORER_DB;
USE SCHEMA APPS;

create warehouse cost_explorer_wh
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 30
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse to use only with cost explorer app';

CREATE ROLE FINOPS_ROLE;
GRANT ROLE FINOPS_ROLE TO ROLE SYSADMIN; -- always do this step so that the ACCOUNTADMIN can use the role
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE FINOPS_ROLE;

-- After app is deployed.
GRANT USAGE ON STREAMLIT COST_EXPLORER_DB.APPS.SNOWFLAKE_COST_EXPLORER TO ROLE <role>;
