-- =====================================================================
-- Data Validation Framework — Metadata & Results Schema
-- =====================================================================
-- Run this once per environment. Adjust database/schema names as needed.

CREATE SCHEMA IF NOT EXISTS DQ_FRAMEWORK;
USE SCHEMA DQ_FRAMEWORK;

-- ---------------------------------------------------------------------
-- 1. Rule definitions — this is the config table that makes the
--    framework transferable across any dataset. Adding validation
--    for a new table = inserting rows here, not writing new code.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE VALIDATION_RULES (
    RULE_ID          NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    DATABASE_NAME    STRING NOT NULL,
    SCHEMA_NAME      STRING NOT NULL,
    TABLE_NAME       STRING NOT NULL,
    COLUMN_NAME      STRING,                      -- NULL for table-level rules
    RULE_TYPE        STRING NOT NULL,              -- see RULE_TYPE values below
    RULE_PARAMS      VARIANT,                      -- flexible JSON params per rule type
    SEVERITY         STRING NOT NULL DEFAULT 'ERROR',  -- ERROR | WARN
    IS_ACTIVE        BOOLEAN NOT NULL DEFAULT TRUE,
    DESCRIPTION      STRING,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RULE_ID)
);

-- RULE_TYPE values supported by the engine (01_engine.py):
--   NOT_NULL      -> RULE_PARAMS: {}                                     (col must not be null)
--   UNIQUE        -> RULE_PARAMS: {}                                     (col or combo unique)
--   RANGE         -> RULE_PARAMS: {"min": 0, "max": 100}
--   REGEX         -> RULE_PARAMS: {"pattern": "^[A-Z]{2}\\d{4}$"}
--   ENUM          -> RULE_PARAMS: {"allowed": ["A","B","C"]}
--   REFERENTIAL   -> RULE_PARAMS: {"ref_table": "DB.SCH.TBL", "ref_col": "ID"}
--   FRESHNESS     -> RULE_PARAMS: {"max_lag_hours": 26}                  (col must be a timestamp)
--   ROW_COUNT_MIN -> RULE_PARAMS: {"min_rows": 1}
--   ROW_COUNT_DRIFT -> RULE_PARAMS: {"lookback_days": 7, "max_pct_change": 0.30}
--   CUSTOM_SQL    -> RULE_PARAMS: {"sql": "SELECT COUNT(*) AS FAILS FROM ... WHERE <bad condition>"}

-- ---------------------------------------------------------------------
-- 2. Run header — one row per validation run (a "run" = one call to
--    run_validation() for one table, or a batch across many tables)
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE VALIDATION_RUNS (
    RUN_ID           STRING NOT NULL,              -- UUID generated by the engine
    TABLE_NAME       STRING NOT NULL,
    STARTED_AT       TIMESTAMP_NTZ,
    FINISHED_AT      TIMESTAMP_NTZ,
    RULES_EVALUATED  NUMBER,
    RULES_PASSED     NUMBER,
    RULES_FAILED     NUMBER,
    RULES_WARNED     NUMBER,
    OVERALL_STATUS   STRING,                       -- PASS | FAIL | WARN
    PRIMARY KEY (RUN_ID)
);

-- ---------------------------------------------------------------------
-- 3. Rule-level results — one row per rule per run, with sampled
--    failing keys so triage doesn't start from a bare count.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE VALIDATION_RESULTS (
    RESULT_ID        NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID           STRING NOT NULL,
    RULE_ID          NUMBER NOT NULL,
    TABLE_NAME       STRING NOT NULL,
    COLUMN_NAME      STRING,
    RULE_TYPE        STRING NOT NULL,
    SEVERITY         STRING NOT NULL,
    CHECK_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORDS_CHECKED  NUMBER,
    RECORDS_FAILED   NUMBER,
    FAIL_PCT         FLOAT,
    STATUS           STRING NOT NULL,              -- PASS | FAIL | WARN | ERROR (engine error)
    SAMPLE_FAILURES  VARIANT,                       -- array of sample offending rows/keys
    ERROR_MESSAGE    STRING,                        -- populated if the check itself errored
    PRIMARY KEY (RESULT_ID)
);

-- ---------------------------------------------------------------------
-- 4. Convenience view: latest status per table, for dashboards / gating
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW VALIDATION_LATEST_STATUS AS
SELECT
    r.TABLE_NAME,
    r.RUN_ID,
    r.FINISHED_AT,
    r.OVERALL_STATUS,
    r.RULES_EVALUATED,
    r.RULES_PASSED,
    r.RULES_FAILED,
    r.RULES_WARNED
FROM VALIDATION_RUNS r
QUALIFY ROW_NUMBER() OVER (PARTITION BY r.TABLE_NAME ORDER BY r.FINISHED_AT DESC) = 1;
